---
-   hosts: all:!localhost:!ansible-master
    remote_user: root
    tasks:
      - name: Create user
        command: useradd -n {{ ansible_user.name }} creates=/home/{{ user }}
        sudo: true

      - name: Set user password
        shell: usermod -p $(echo '{{ ansible_user.pass }}' | openssl passwd -1 -stdin) {{ ansible_user.name }}
        sudo: true
     
      - name: Sudoers | update sudoers file and validate
        lineinfile: "dest=/etc/sudoers
          insertafter=EOF
          line='{{ ansible_user.name }} ALL=(ALL) NOPASSWD: ALL'
          regexp='{{ ansible_user.name }} ALL=(ALL) NOPASSWD: ALL'
          state=present"
        sudo: true